const desktop={
	menuItem:{
		tianqi:{
			title:'天气',
			icon:'entry/img/main_item_right.png'
		},
		chifan:{
			title:'吃饭',
			icon:'entry/img/main_item_right.png'
		},
		zhongliang:{
			title:'重量',
			icon:'entry/img/main_item_right.png'
		},
		quyu:{
			title:'组团',
			icon:'entry/img/main_item_right.png'
		},
		jibing:{
			title:'疾病',
			icon:'entry/img/main_item_right.png'
		},
		huangyuangui:{
			title:'黄缘龟',
			icon:'entry/img/main_item_right.png'
		},
		sanjiaoyazi:{
			title:'三趾',
			icon:'entry/img/main_item_right.png'
		}
	},
	menuOrder:[
		'tianqi',
		'chifan',
		'zhongliang',
		'quyu',
		'jibing',
		'huangyuangui',
		'sanjiaoyazi'
	]
}